/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Bpge2mgMvzE
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function Hero() {
  return (
    <section
      className="relative bg-cover bg-center text-white"
      style={{
        backgroundImage: "url('/bg.jpg')",
      }}
    >
      <nav className="container mx-auto px-4 py-6 flex justify-between items-center">
        <div className="flex space-x-4">
          <FlagIcon className="text-white h-6 w-6" />
          <div className="flex space-x-6">
            <a className="hover:underline" href="#">
              Why Sparked
            </a>
            <a className="hover:underline" href="#">
              Products
            </a>
            <a className="hover:underline" href="#">
              Solutions
            </a>
            <a className="hover:underline" href="#">
              Resources
            </a>
          </div>
        </div>
        <div className="flex space-x-4">
          <Button className="bg-transparent hover:bg-white hover:text-black text-white border border-white">
            Log in
          </Button>
          <Button className="bg-white text-black">Join now</Button>
        </div>
      </nav>
      <div className="container mx-auto px-4 py-20">
        <div className="max-w-3xl">
          <p className="text-sm font-medium">
            Brand new release: v1.2 Professional
          </p>
          <h1 className="text-6xl font-bold leading-tight mt-4">
            Powerful version control,
            <br />
            seamless collaboration{"\n              "}
          </h1>
          <p className="mt-6 text-lg">
            Sparked is an innovative platform designed to revolutionize
            collaborative software development and empower teams to achieve
            their goals with unmatched efficiency. Built with developers in mind
          </p>
          <div className="mt-8 flex space-x-4">
            <Button className="bg-white text-black">Start Trial</Button>
            <Input className="w-64" placeholder="Your email" type="email" />
            <Button className="bg-transparent hover:bg-white hover:text-black text-white border border-white">
              Subscribe
            </Button>
          </div>
        </div>
      </div>
      <div className="container mx-auto px-4 py-8">
        <div className="flex justify-center space-x-8">
          <GithubIcon className="h-6 w-6 text-white" />
          <GitlabIcon className="h-6 w-6 text-white" />
          <ChromeIcon className="h-6 w-6 text-white" />
          <ComputerIcon className="h-6 w-6 text-white" />
          <AppleIcon className="h-6 w-6 text-white" />
          <GitlabIcon className="h-6 w-6 text-white" />
        </div>
      </div>
    </section>
  );
}

function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function GitlabIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  );
}

function ChromeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  );
}

function ComputerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="8" x="5" y="2" rx="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" />
      <path d="M6 18h2" />
      <path d="M12 18h6" />
    </svg>
  );
}

function AppleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  );
}
