/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2LFLkheoi9Z
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function LoginForm() {
  return (
    <div className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900">
      <div className="grid place-items-center mx-2 my-20 sm:my-auto">
        <div className="w-11/12 p-12 sm:w-8/12 md:w-6/12 lg:w-5/12 xl:w-4/12 2xl:w-3/12 px-6 py-10 sm:px-10 sm:py-6 bg-white rounded-lg shadow-md lg:shadow-lg dark:bg-gray-800">
          <h2 className="text-center font-semibold text-3xl lg:text-4xl text-gray-800 dark:text-white">Login</h2>
          <form className="mt-10">
            <div>
              <input
                className="mt-1 block w-full bg-gray-100 dark:bg-gray-700 dark:text-gray-300 py-2 px-3 rounded-lg focus:outline-none"
                placeholder="Email Address"
                type="email"
              />
            </div>
            <div className="mt-4">
              <input
                className="mt-1 block w-full bg-gray-100 dark:bg-gray-700 dark:text-gray-300 py-2 px-3 rounded-lg focus:outline-none"
                placeholder="Password"
                type="password"
              />
            </div>
            <div className="flex justify-between items-baseline">
              <Link className="text-sm hover:underline dark:text-gray-200" href="#">
                Forgot password?
              </Link>
              <Link className="text-sm hover:underline dark:text-gray-200" href="#">
                Create an account
              </Link>
            </div>
            <Button className="w-full py-3 bg-gray-800 text-white rounded-lg mt-4">Login</Button>
          </form>
          <div className="py-6">
            <div className="flex items-center justify-center">
              <span className="border-b w-1/5 md:w-1/4" />
              <span className="text-xs text-center text-gray-500 uppercase">or login with</span>
              <span className="border-b w-1/5 md:w-1/4" />
            </div>
          </div>
          <div className="flex justify-center">
            <Button className="w-24 h-10 mr-2 flex justify-center items-center" variant="outline">
              <img alt="Google" className="h-5 w-5" src="/placeholder.svg" />
            </Button>
            <Button className="w-24 h-10 flex justify-center items-center" variant="outline">
              <img alt="GitHub" className="h-5 w-5" src="/placeholder.svg" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
